import { Fragment } from 'react'
import Head from 'next/head'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import { Container } from 'react-bootstrap'

const Layout = (props) => {
  const {
    title = 'Bookit',
    description = 'default description',
    content = 'default Generated by create next app'
  } = props
  return (
    <Fragment>
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <link rel="icon" href="/favicon.ico" />

        <title>{title}</title>
        <meta name={description} content={content} />
      </Head>
      <Header />

      <main className='py-5'>
        <Container>{props.children}</Container>
      </main>

      <Footer />
    </Fragment>
  )
}

export default Layout
